name: Tests

on:
  pull_request:
    branches: [main, master]

  push:
    branches: [main, master]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      
      - name: Copy .env file
        run: |
          cp .env.ci .env

      - name: Run Composer
        run: |
          composer install --no-interactions

      - name: Generate Key
        run: |
          php artisan key:generate

      - name: Run test suite
        run: |
          php artisan test
        